; TODO INSERT CONFIG CODE HERE USING CONFIG BITS GENERATOR
    
    #include "p16F628A.inc"	; Incluindo o pic de uso
				;Configuração inicial do microcontrolador
	__CONFIG _FOSC_HS & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _BOREN_ON & _LVP_OFF & _CPD_OFF & _CP_OFF
; Página de memória	
#DEFINE	BANK0	BCF STATUS,RP0	;SETA BANK 0 DE MEMÓRIA
#DEFINE	BANK1	BSF STATUS,RP0	;SETA BANK 1 DE MAMÓRIA
; Definição das variáveis
    CBLOCK  0x20
        TEMPO1
        TEMPO2
    ENDC

;Início do programa
    ORG     0x00
    GOTO    inicio
; Quando há interrupção
    ORG     0x04
    RETFIE

; O DELAY PRINCIPAL DURA 1ms, POIS POSSUI 5 INSTRUÇÕES (5us) E É
; RODADO 200 VEZES (TEMPO1). PORTANTO 200 * 5us = 1ms.
; O DELAY PRINCIPAL É RODADO TANTAS VEZES QUANTO FOR O VALOR DE
; TEMPO2, O QUAL É INICIADO COM O VALOR PASSADO EM W.


DELAY
	MOVWF	TEMPO2	    ;INICIA TEMPO 2 COM O VALOR
			    ;PASSADO EM W
DL1	 
	MOVLW	.200
	MOVWF	TEMPO1

DL2			    ;ESTE DELAY DURA 1ms (5*200)
	NOP
	NOP
	DECFSZ	TEMPO1,F    ;DECREMENTA TEMPO1. ACABOU?
	GOTO	DL2	    ;NÃO, CONTINUA AGUARDANDO
			    ;SIM

	DECFSZ	TEMPO2,F    ;DECREMENTA TEMPO2. ACABOU?
	GOTO	DL1	    ;NÃO, CONTINUA AGUARDANDO
			    ;SIM
	RETURN

inicio
	BANK1			;ALTERA PARA O BANCO 1
	MOVLW	B'00000000'
	MOVWF	TRISA		;DEFINE ENTRADAS E SAÍDAS DO PORTA
	MOVLW	B'00000000'
	MOVWF	TRISB		;DEFINE ENTRADAS E SAÍDAS DO PORTB
	MOVLW	B'10000100'
	MOVWF	OPTION_REG	;DEFINE OPÇÕES DE OPERAÇÃO
	MOVLW	B'00000000'
	MOVWF	INTCON		;Desliga todas as interrupções
	BANK0			;RETORNA PARA O BANCO Zero
	MOVLW	B'00000111'
	MOVWF	CMCON		;Desliga os comparadores e habilita os pinos como entrada e saída
	
start
	MOVLW	.250
	CALL	DELAY
	MOVLW	.250
	CALL	DELAY
	BSF		PORTB,0
	MOVLW	.250
	CALL	DELAY
	MOVLW	.250
	CALL	DELAY
	BSF		PORTB,1
	MOVLW	.250
	CALL	DELAY
	MOVLW	.250
	CALL	DELAY
	BSF		PORTB,2
	MOVLW	.250
	CALL	DELAY
	MOVLW	.250
	CALL	DELAY
	BSF		PORTB,3
	
	MOVLW	.250
	CALL	DELAY
	MOVLW	.250
	CALL	DELAY
	BSF		PORTB,4
	MOVLW	.250
	CALL	DELAY
	MOVLW	.250
	CALL	DELAY
	BSF		PORTB,5
	MOVLW	.250
	CALL	DELAY
	MOVLW	.250
	CALL	DELAY
	BSF		PORTB,6
	MOVLW	.250
	CALL	DELAY
	MOVLW	.250
	CALL	DELAY
	BSF		PORTB,7
	
	MOVLW	.200
	CALL	DELAY
	BCF		PORTB,7
	MOVLW	.200
	CALL	DELAY
	BCF		PORTB,6
	MOVLW	.200
	CALL	DELAY
	BCF		PORTB,5
	MOVLW	.200
	CALL	DELAY
	BCF		PORTB,4
	
	MOVLW	.200
	CALL	DELAY
	BCF		PORTB,3
	MOVLW	.200
	CALL	DELAY
	BCF		PORTB,2
	MOVLW	.200
	CALL	DELAY
	BCF		PORTB,1
	MOVLW	.200
	CALL	DELAY
	BCF		PORTB,0
	
	GOTO	start
	END	; Este final é obrigatório