CREATE DATABASE FAMILIA;
USE FAMILIA;

CREATE TABLE RESIDENCIA (
    IDResidencia INTEGER NOT NULL AUTO_INCREMENT,
    UF VARCHAR(2),
    Cidade VARCHAR(50),
    Bairro VARCHAR(50),
    Rua VARCHAR(150),
    CEP VARCHAR(8),
    PRIMARY KEY PK_RESIDENCIA (IDResidencia)
);

CREATE TABLE PESSOA (
    IDPessoa INTEGER NOT NULL AUTO_INCREMENT,
    IDResidencia INTEGER NOT NULL,
    NOME VARCHAR(100),
    ESCOLARIDADE VARCHAR(50),
    dataNascimento DATE,
    dataFalecimento DATE,
    PRIMARY KEY PK_PESSOA (IDPessoa),
    FOREIGN KEY FK_RESIDENCIA(IDResidencia) REFERENCES RESIDENCIA(IDResidencia) ON DELETE RESTRICT
);

CREATE TABLE CASAMENTO(
    IDCasamento INTEGER NOT NULL AUTO_INCREMENT,
    IDPessoa1 INTEGER NOT NULL,
    IDPessoa2 INTEGER NOT NULL,
    dataReligioso DATE,
    dataCivil DATE,
    dataUniaoEstavel DATE,
    dataDissolucao DATE,
    motivoDissolucao VARCHAR(10),
    PRIMARY KEY PK_CASAMENTO(IDCasamento),
    FOREIGN KEY FK_PESSOA1(IDPessoa1) REFERENCES PESSOA(IDPessoa) ON DELETE RESTRICT,
    FOREIGN KEY FK_PESSOA2(IDPessoa2) REFERENCES PESSOA(IDPessoa) ON DELETE RESTRICT
);

CREATE TABLE GRAU_PARENTESCO (
    IDGrau_Parentesco INTEGER NOT NULL AUTO_INCREMENT,
    IDPai INTEGER NOT NULL,
    IDMae INTEGER NOT NULL,
    IDPessoa INTEGER NOT NULL,
    Adotivo VARCHAR(1),
    PRIMARY KEY PK_GRAU_PARENTESCO(IDGrau_Parentesco),
    FOREIGN KEY FK_PESSOA(IDPessoa) REFERENCES PESSOA(IDPessoa) ON DELETE RESTRICT,
    FOREIGN KEY FK_PAI(IDPai) REFERENCES PESSOA(IDPessoa) ON DELETE RESTRICT,
    FOREIGN KEY FK_MAE(IDMae) REFERENCES PESSOA(IDPessoa) ON DELETE RESTRICT
);

# Comando 1
SELECT DISTINTC Cidade FROM RESIDENCIA WHERE UF = 'PR' ORDER BY Cidade DESC;

# Comando 2
SELECT NOME, PESSOA.IDResidencia FROM PESSOA
INNER JOIN RESIDENCIA ON PESSOA.IDResidencia = RESIDENCIA.IDResidencia
WHERE RESIDENCIA.Cidade LIKE 'PONTA GROSSA' OR 'LONDRINA' OR 'MARINGÁ' OR 'CURITIBA'
ORDER BY RESIDENCIA.Cidade ASC, NOME DESC;

# Comando 3
SELECT COUNT(*) AS NROESC, A.ESCOLARIDADE FROM PESSOA AS A
GROUP BY A.ESCOLARIDADE DESC;

# Comando 4
SELECT NOME FROM PESSOA P, CASAMENTO C
WHERE (P.IDPESSOA = C.IDPESSOA1 OR P.IDPESSOA = C.IDPESSOA2)
AND DATADISSOLUCAO IS NULL;

# Comando 5
SELECT NOME
FROM PESSOA P, GRAU_PARENTESCO G
WHERE P.IDPESSOA = G.IDPESSOA
AND G.IDPAI = (
	SELECT P.IDPESSOA FROM PESSOA P
	WHERE P.NOME = 'Ana Furtado Guimarães'
)
AND G.IDMAE = (
	SELECT P.IDPESSOA FROM PESSOA P
	WHERE P.NOME = 'Dirceu Silvério'
);

# Comando 6
SELECT NOME
FROM PESSOA P, GRAU_PARENTESCO G
WHERE P.IDPESSOA = G.IDPESSOA
AND P.NOME NOT IN ('Juarez Jorge da Silva')
AND G.IDPAI = (
	SELECT G.IDPAI FROM GRAU_PARENTESCO G, PESSOA P
	WHERE P.IDPESSOA = G.IDPESSOA
	AND P.NOME = 'Juarez Jorge da Silva'
)
AND G.IDMAE = (
	SELECT G.IDMAE FROM GRAU_PARENTESCO G, PESSOA P
	WHERE P.IDPESSOA = G.IDPESSOA
	AND P.NOME = 'Juarez Jorge da Silva'
)
GROUP BY P.NOME ASC;

# Comando 7
SELECT P.NOME, COUNT(*) QTDE
FROM PESSOA P, CASAMENTO C
WHERE (P.IDPESSOA = C.IDPESSOA1 OR P.IDPESSOA = C.IDPESSOA2)
AND P.dataFalecimento is not null
GROUP BY P.NOME
ORDER BY QTDE desc  
LIMIT 1;

# Comando 8
DELETE FROM RESIDENCIA
WHERE RESIDENCIA.IDResidencia NOT IN(
	SELECT IDResidencia FROM PESSOA
);

# Comando 9
ALTER TABLE `PESSOA` ADD FOREIGN KEY (`IDResidencia`) REFERENCES `RESIDENCIA` (`IDResidencia`);

# Comando 10
CREATE TABLE GRAU_PARENTESCO (
    IDGrau_Parentesco INTEGER NOT NULL AUTO_INCREMENT,
    IDPai INTEGER NOT NULL,
    IDMae INTEGER NOT NULL,
    IDPessoa INTEGER NOT NULL,
    Adotivo VARCHAR(1),
    PRIMARY KEY PK_GRAU_PARENTESCO(IDGrau_Parentesco),
    FOREIGN KEY FK_PESSOA(IDPessoa) REFERENCES PESSOA(IDPessoa) ON DELETE RESTRICT,
    FOREIGN KEY FK_PAI(IDPai) REFERENCES PESSOA(IDPessoa) ON DELETE RESTRICT,
    FOREIGN KEY FK_MAE(IDMae) REFERENCES PESSOA(IDPessoa) ON DELETE RESTRICT
);