USE BIBLIOTECA;

DELIMITER $$
	CREATE PROCEDURE AcervoEditora() 
    BEGIN
		SELECT EDITORA.Nome, ACERVO.Titulo
		FROM EDITORA, ACERVO
		WHERE EDITORA.CodEditora = ACERVO.CodEditora
		ORDER BY 1 DESC;
	END
$$
DELIMITER;
CALL AcervoEditora;
DROP PROCEDURE AcervoEditora;

DELIMITER $$
	CREATE PROCEDURE ACERVO_ANO(IN ANOP INT) BEGIN
		SELECT Titulo, DtEdicao
        FROM ACERVO	
        WHERE YEAR(DtEdicao) = ANOP
        ORDER BY DtEdicao DESC;
	END
$$
DELIMITER;
CALL ACERVO_ANO(2005);

DELIMITER $$
	CREATE PROCEDURE ANALISE_ACERVO (OUT MAIOR_ACERVO DATE) BEGIN
		SELECT MAX(DtEdicao) INTO MAIOR_ACERVO
        FROM ACERVO;
	END
$$
DELIMITER;
SET @MAIOR = 0;
CALL ANALISE_ACERVO(@MAIOR);
SELECT @MAIOR AS MAIOR_ACERVO;

CREATE TABLE PRODUTO (
	IDPRODUTO INTEGER NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    QTDE_ESTOQUE NUMERIC(12,4) DEFAULT 0,
    VLR_CUSTO NUMERIC(12,2),
    MARGEM_LUCRO NUMERIC(8,2),
    PRIMARY KEY PK_PRODUTO(IDPRODUTO)
);

CREATE TABLE VENDA (
	IDVENDA INTEGER NOT NULL AUTO_INCREMENT,
    DT_VENDA DATE,
    QTDE_VENDA NUMERIC(12,4),
    IDPRODUTO INTEGER,
    PRIMARY KEY PK_VENDA(IDVENDA),
    FOREIGN KEY FK_PRODUTO(IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO) ON DELETE RESTRICT
);

INSERT INTO PRODUTO (
	NOME,
    QTDE_ESTOQUE,
    VLR_CUSTO,
    MARGEM_LUCRO
) VALUES (
	"Blu-Ray Player",
    10,
    155,
    80
);

INSERT INTO PRODUTO (
	NOME,
    QTDE_ESTOQUE,
    VLR_CUSTO,
    MARGEM_LUCRO
) VALUES (
	"TV LED 3D Full HD 40",
    15,
    1580,
    120
);

SELECT * FROM PRODUTO;